### ISSUE TITLE
Error: Undefined variable: "$color-warning"

### ISSUE THREAD

**Issue by bmcandr** [carpentries/carpentries-theme#10]
Hey there,

I'm encountering the following error when running `make serve` in a Carpentries lesson repo:

```sh
bundle exec jekyll serve
Configuration file: /Users/username/Desktop/repos/geospatial-python/_config.yml
            Source: /Users/username/Desktop/repos/geospatial-python
       Destination: /Users/username/Desktop/repos/geospatial-python/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
      Remote Theme: Using theme carpentries/carpentries-theme
  Conversion error: Jekyll::Converters::Scss encountered an error while converting 'assets/css/lesson.scss':
                    Undefined variable: "$color-warning". on line 56
jekyll 3.9.0 | Error:  Undefined variable: "$color-warning". on line 56
```

Looks like `$color-warning` is a new addition, but it isn't defined in the [code boxes section of lesson.scss](https://github.com/carpentries/carpentries-theme/blob/30bc0a8f7a697ab18d1666ae5f4b1eaf8178d4b6/assets/css/lesson.scss#L25) as the other code box colors are. 

Edit: [found it](https://github.com/tobyhodges/carpentries-theme/blob/37378c5789b75470435b8cf89096aed26383e73e/assets/css/lesson.scss#L27). Probably just missed while cherry picking!

**Comment by ikirker** [comment]
Broken here, I think? <https://github.com/carpentries/carpentries-theme/commit/9519f24156e14ac674027f4f4d21fe8d6d0475f9#diff-261aa6907f9d70ab43978efe25de50d908dc9853c9e2e43f9887827a6e829f84>

**Comment by rbavery** [comment]
I think @fmichonneau fixed it here today: https://github.com/carpentries/carpentries-theme/commit/c8587d059b8c00dc9eca1504b591ef5348aec573

Thanks! My build is completing now.
