### ISSUE TITLE
Remote theme suddenly not working 

### ISSUE THREAD

**Issue by ocaisa** [carpentries/carpentries-theme#12]
In the last hour or so pulling the remote theme has suddenly stopped working. I saw there were some recent commits in the same timeframe. The error I am seeing is:
```
/path-to/hpc-intro/.vendor/bundle/ruby/2.7.0/gems/jekyll-remote-theme-0.4.2/lib/jekyll-remote-theme/downloader.rb:67:in `raise_unless_sucess': 404 - Not Found (Jekyll::RemoteTheme::DownloadError)
```

**Comment by ocaisa** [comment]
It's also affecting the CI runs, https://github.com/carpentries-incubator/hpc-intro/runs/1951854913

**Comment by fmichonneau** [comment]
Thanks for the heads up. I had renamed the default branch from `master` to `main`. I just switched back.

**Comment by ocaisa** [comment]
Confirmed, that's working again

**Comment by ocaisa** [comment]
Thanks!

**Comment by fmichonneau** [comment]
upstream reference: https://github.com/benbalter/jekyll-remote-theme/issues/84
