### ISSUE TITLE
local build fails on MacOS Big Sur

### ISSUE THREAD

**Issue by tobyhodges** [carpentries/carpentries-theme#21]
My local builds have stopped working, encountering some issue when trying to install `ffi`. After a bit of digging around, I have not been able to troubleshoot the problem. But, because local builds are working okay for lessons based on the most recent version of carpentries/styles, and I get the same error on multiple different lessons using the remote theme, I think I have isolated it to the remote theme and this is the right place to report the issue. I can provide the complete output of `make serve` if you think that will be helpful, but the "business end" with details of the error is copied below (with local paths redacted).

```
error: libtool: no output file specified (specify with -o output)
Usage: libtool -static [-] file [...] [-filelist listfile[,dirname]] [-arch_only arch] [-sacLT] [-no_warning_for_no_symbols]
Usage: libtool -dynamic [-] file [...] [-filelist listfile[,dirname]] [-arch_only arch] [-o output] [-install_name name]
[-compatibility_version #] [-current_version #] [-seg1addr 0x#] [-segs_read_only_addr 0x#] [-segs_read_write_addr 0x#]
[-seg_addr_table <filename>] [-seg_addr_table_filename <file_system_path>] [-all_load] [-noall_load]
make[4]: *** [libffi_convenience.la] Error 1
make[3]: *** [all-recursive] Error 1
make[2]: *** [all] Error 2
make[1]: ***
["/path/to/lesson/repository/redacted/.vendor/bundle/ruby/2.7.0/gems/ffi-1.15.3/ext/ffi_c/libffi-x86_64-darwin20"/.libs/libffi_convenience.a]
Error 2

make failed, exit code 2

Gem files will remain installed in
/path/to/lesson/repository/redacted/.vendor/bundle/ruby/2.7.0/gems/ffi-1.15.3 for inspection.
Results logged to
/path/to/lesson/repository/redacted/.vendor/bundle/ruby/2.7.0/extensions/x86_64-darwin-20/2.7.0/ffi-1.15.3/gem_make.out

An error occurred while installing ffi (1.15.3), and Bundler cannot continue.
Make sure that `gem install ffi -v '1.15.3' --source 'https://rubygems.org/'` succeeds before bundling.

In Gemfile:
  github-pages was resolved to 218, which depends on
    github-pages-health-check was resolved to 1.17.2, which depends on
      typhoeus was resolved to 1.4.0, which depends on
        ethon was resolved to 0.14.0, which depends on
          ffi
make: *** [serve] Error 5
```

**Comment by zkamvar** [comment]
I wonder if it's worthwhile to raise an issue on the ffi issue tracker? They seem to have a lot of weird issues with libtool popping up.

**Comment by tobyhodges** [comment]
This issue is resolved on my machine. I'm afraid I don't have the full history of exactly how I fixed it but I can say that it turned out to be a problem associated with `conda` and the key step towards fixing it was removing Anaconda.
