### ISSUE TITLE
Sync with the Carpentries styles repository

### ISSUE THREAD

**Issue by jhlegarreta** [carpentries/carpentries-theme#22]
It is a while now since the Carpentries style repository supports inline images:
https://github.com/carpentries/styles/pull/602

However, they are rendered as inline images because those changes have not been brought into the remote theme.

It would be helpful if that feature was available.

Cross-referencing https://github.com/carpentries-incubator/SDC-BIDS-dMRI/issues/197

Thanks.

**Comment by fmichonneau** [comment]
I just re-synced the remote theme and the inline images are now supported. Thanks!

**Comment by jhlegarreta** [comment]
@fmichonneau thanks :100:. It is working like a charm:
https://carpentries-incubator.github.io/SDC-BIDS-dMRI/diffusion_tensor_imaging/index.html

**Comment by fmichonneau** [comment]
Excellent! We also now have KaTeX so you could write some of these equations directly in the markdown files

**Comment by jhlegarreta** [comment]
> Excellent! We also now have KaTeX so you could write some of these equations directly in the markdown files

Great. Not sure when that was introduced, but it looks like some of the LaTeX syntax we already have in our episodes does not get rendered correctly: e.g. `$mm^2/s$` in that same
https://carpentries-incubator.github.io/SDC-BIDS-dMRI/diffusion_tensor_imaging/index.html
