### ISSUE TITLE
Wrong site.repository value

### ISSUE THREAD

**Issue by anenadic** [carpentries/carpentries-theme#26]
In the link "If you teach this lesson, please tell the authors and provide feedback by opening an issue in the source repository" for beta lessons -  the link URL is incorrectly set to `https://github.com/<USERNAME>/<PROJECT>/issues`

<img width="1431" alt="image" src="https://user-images.githubusercontent.com/631719/195073207-bad79c88-8f9e-4c91-8215-51da38c9261d.png">

It should be reading the `site.repository` value but something is going wrong. Perhaps because  https://github.com/carpentries/carpentries-theme/blob/main/_includes/life_cycle.html is missing from the gh-pages branch (and this is where the reading of the variable is happening)?

**Comment by tobyhodges** [comment]
Thanks for reporting this, @anenadic. I believe it is fixed now in ecb8c46
