### ISSUE TITLE
Links are difficult to distinguish from regular text (colours are too similar)

### ISSUE THREAD

**Issue by baileythegreen** [carpentries/carpentries-theme#7]
The dark blue colour of links in the bootstrap theme is not much different from black, and links are not underlined except on hover, so they can be difficult to spot.

I propose changing the colour of links generally, as I have done for this forked lesson website for a workshop being run now:

https://edcarp.github.io/genomics-r-intro/

Note: The links here have been made a bright blue. I have also changed the colour for links that have already been visited, and that is currently a bright pink, but this change is not necessary, or the colour could be modified to something else.

I can put together a PR for this, but would like to know if it would be preferable for the new CSS to be placed inside of the bootstrap file, or whether you would prefer a separate CSS file (which would also require adding a line to the `base.html`,  and `workshop.html` layout files.

**Comment by baileythegreen** [comment]
@fmichonneau

I'm unsure who the best person to tag here is, but I at least know you're on here regularly. Can we do something about this? I know the template is being reconsidered, but I literally can not tell the links apart from normal text. I can't be the only one with this issue.

**Comment by ErinBecker** [comment]
Thank you for this issue @baileythegreen and for re-upping it for attention. @zkamvar could you please advise?

**Comment by zkamvar** [comment]
My recommendation is to add the CSS you came up with to insert it here with your PR:

https://github.com/carpentries/carpentries-theme/blob/c8587d059b8c00dc9eca1504b591ef5348aec573/assets/css/lesson.scss#L218-L226

That being said, I don't know how the remote themes are updated in relation to the styles repository and will defer to @fmichonneau for advice.
